# Generated by Django 6.0.2 on 2026-02-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_entries', to='indexer.person')),
            ],
            options={
                'verbose_name_plural': 'index entries',
                'ordering': ['person__slug', 'subject__slug'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='indexer.book')),
            ],
            options={
                'ordering': ['book', 'page_start', 'page_end'],
            },
        ),
        migrations.CreateModel(
            name='IndexEntryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('index_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_references', to='indexer.indexentry')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_references', to='indexer.reference')),
            ],
            options={
                'ordering': ['order', 'reference__book__slug', 'reference__page_start'],
            },
        ),
        migrations.AddField(
            model_name='indexentry',
            name='references',
            field=models.ManyToManyField(related_name='index_entries', through='indexer.IndexEntryReference', to='indexer.reference'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='indexer.subject')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='indexentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='index_entries', to='indexer.subject'),
        ),
        migrations.CreateModel(
            name='SubjectLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=35)),
                ('label', models.CharField(max_length=500)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='indexer.subject')),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=35)),
                ('label', models.CharField(max_length=500)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='indexer.book')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('book', 'language', 'label')},
            },
        ),
        migrations.CreateModel(
            name='PersonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=35)),
                ('label', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='indexer.person')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('person', 'language', 'label')},
            },
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['book', 'page_start'], name='indexer_ref_book_id_eefbaf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indexentryreference',
            unique_together={('index_entry', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectlabel',
            unique_together={('subject', 'language', 'label')},
        ),
    ]
