# Generated by Django 6.0.2 on 2026-02-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0002_refactor_index_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('book', 'Book'), ('chapter', 'Chapter'), ('article', 'Article'), ('other', 'Other')], db_index=True, default='book', max_length=20)),
                ('canonical_title', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500)),
                ('isbn_issn', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='indexer.work')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='reference',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='indexer.work'),
        ),
        migrations.CreateModel(
            name='WorkTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=35)),
                ('label', models.CharField(max_length=500)),
                ('sort_key', models.CharField(blank=True, max_length=500)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='indexer.work')),
            ],
            options={
                'ordering': ['language'],
                'indexes': [models.Index(fields=['work', 'language'], name='indexer_wt_work_lang_idx'), models.Index(fields=['language', 'label'], name='indexer_wt_lang_label_idx')],
                'unique_together': {('work', 'language', 'label')},
            },
        ),
    ]
