# Generated by Django 6.0.2 on 2026-03-15 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0008_frbr_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('gnd', 'GND'), ('isni', 'ISNI'), ('orcid', 'ORCID')], db_index=True, max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_identifiers', to='indexer.agent')),
            ],
            options={
                'ordering': ['identifier_type', 'value'],
                'indexes': [models.Index(fields=['agent', 'identifier_type'], name='indexer_pi_agent_type_idx'), models.Index(fields=['identifier_type', 'value'], name='indexer_pi_type_value_idx')],
                'unique_together': {('agent', 'identifier_type'), ('identifier_type', 'value')},
            },
        ),
    ]
