# Generated by Django 6.0.2 on 2026-08-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexer', '0012_reference_locator_cross_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('match_type', models.CharField(choices=[('title', 'Title'), ('isbn', 'ISBN'), ('year', 'Year'), ('manual', 'Manual')], default='title', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='indexer.manifestation')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestation_suggestions', to='indexer.reference')),
            ],
            options={
                'ordering': ['-score', 'manifestation__slug'],
                'indexes': [
                    models.Index(fields=['reference', 'status'], name='indexer_ms_ref_status_idx'),
                    models.Index(fields=['manifestation', 'score'], name='indexer_ms_mf_score_idx'),
                ],
                'unique_together': {('reference', 'manifestation')},
            },
        ),
    ]
